#ifndef TWICE_QT_MAINWINDOW_ACTIONS_H
#define TWICE_QT_MAINWINDOW_ACTIONS_H

namespace MainWindowAction {

enum {
	OPEN_ROM,
	LOAD_SYSTEM_FILES,
	LOAD_IMAGE_FILE,
	INSERT_CART,
	EJECT_CART,
	LOAD_SAVE_FILE,
	UNLOAD_SAVE_FILE,
	SET_SAVETYPE_AUTO,
	SET_SAVETYPE_NONE,
	SET_SAVETYPE_EEPROM_512B,
	SET_SAVETYPE_EEPROM_8K,
	SET_SAVETYPE_EEPROM_64K,
	SET_SAVETYPE_EEPROM_128K,
	SET_SAVETYPE_FLASH_256K,
	SET_SAVETYPE_FLASH_512K,
	SET_SAVETYPE_FLASH_1M,
	SET_SAVETYPE_FLASH_8M,
	SET_SAVETYPE_NAND,
	RESET_TO_ROM,
	RESET_TO_FIRMWARE,
	SHUTDOWN,
	RESTORE_INSTANCE,
	TOGGLE_PAUSE,
	TOGGLE_FASTFORWARD,
	LINEAR_FILTERING,
	LOCK_ASPECT_RATIO,
	ROTATE_CLOCKWISE,
	ROTATE_HALFCIRCLE,
	ROTATE_ANTICLOCKWISE,
	ORIENTATION_0,
	ORIENTATION_1,
	ORIENTATION_2,
	ORIENTATION_3,
	SCALE_1X,
	SCALE_2X,
	SCALE_3X,
	SCALE_4X,
	AUTO_RESIZE,
	LERP_AUDIO,
	OPEN_SETTINGS,
	NUM_ACTIONS,
};

enum {
	SAVETYPE_GROUP,
	SCALE_GROUP,
	ROTATION_GROUP,
	ORIENTATION_GROUP,
	NUM_GROUPS,
};

namespace MainWindowMenu {

enum {
	FILE_MENU,
	SAVETYPE_MENU,
	EMULATION_MENU,
	VIDEO_MENU,
	AUDIO_MENU,
	SCALE_MENU,
	ROTATION_MENU,
	ORIENTATION_MENU,
	TOOLS_MENU,
	NUM_MENUS,
};
}

}; // namespace MainWindowAction

#endif
